### PR TITLE
fix/tran 1.19.1

### PR DESCRIPTION
**Pull request by Mapaler**
Thank you for trying to translate. But there's something wrong with Tifa's translation, “un|evolve” writes "未|进化" in Chinese.
There are many Chinese characters in Japanese, Chinese can be directly known. So I use "炎鎖" and "禁窟" to distinguish them.
> Chinese Simplified, Chinese Traditional, Japanese characters exist some foreign characters, a Chinese character has a variety of writing, but most can still recognize.

▼炎鎖の大魔女・マドゥ
4411_zpsqy49mfor
▼禁窟の大魔女・マドゥ
4410_zpst2hqgo9r

"大|魔女" means "Great | Witch","炎|鎖" means "Flame | Chains", "禁|窟" means "Forbidden | Cavern". It's a literal translation of a single Chinese character.
Because you're in a different cultural circle, you probably don't feel. *GungHo* uses a lot of Chinese characters to name its own copyrighted characters, two words at a time. They all sound powerful adjectives. 
<hr>
So, Tifa without intellectual property doesn't have a 2-word adjective.

▼セブンスヘブンの看板娘・ティファ
3298_zpshkfk7k8n
"看板|娘" means "signboard | girl", It's a Japanese word. It's probably that, a waitress in a shop, because of cute so many customers come to, become a shop sign.
Other forms of tifa have no connected and meaningful Chinese characters, descriptions in Chinese characters are not appropriate. So I chose to describe the difference between awakening and leaderskill, "光|横" means "Light | Row".
<hr>
If you want to know the Chinese name of the character, you can visit the

[Friends Systems and Information Websites of P\&D](https://pad.skyozora.com)
(This is a Hong Kong website, are using Traditional Chinese.)
You can use `https://pad.skyozora.com/pets/[card id]` to access card.

If you need a simple conversion. This is a simplified and traditional conversion library.
https://github.com/BYVoid/OpenCC

You can also use my [PADDashFormation](https://github.com/Mapaler/PADDashFormation) project to switch between different languages. Japanese, English, Korean, from official game data; and Chinese from the *pad.skyozora.com*.(Although I get Korean game data, I can't read Korean.)

### CODE REVIEW

**Comment by Mapaler** [comment]
By the way, for some reason in Chinese politics, the means of crossing the Great Wall have been heavily blocked.
My VPS IP is also blocked by the mainland. I can't visit Google right now.
I can't update the APP and refresh the remote subscription.(Of course the money is still withholding.)

**Comment by puzzled-dragon** [comment]
Hi.

Thanks a lot for this detailed explanation !
I was naive and thought that 炎锁 meant "uevo" (= Ultimate Evolution)...
I will refrain from being proactive next time !

Anyway thanks for the translation :)

**Comment by puzzled-dragon** [comment]
As for your second comment, I'm sorry to hear that.
Is there no other way around ?

I must use the Google libs in the app so there is not so much I can do about the subscriptions, etc.
I can send you the APK directly, but you still won't be able to use the store...

I wish you well

**Comment by Mapaler** [comment]
> 
> 
> Hi.
> 
> Thanks a lot for this detailed explanation !
> I was naive and thought that 炎锁 meant "uevo" (= Ultimate Evolution)...
> I will refrain from being proactive next time !
> 
> Anyway thanks for the translation :)

So, "uevo" was "Ultimate Evolution", I thought it was unevolved.
"Ultimate | Evolution" writes "究极(or 终极)|进化" in Chinese.("究极" is a Japanese word, because of video games, Chinese know what it means.)

So, which is Tifa(uevo)? No.3298 or 3299? In China, the most use is 3298, so I named it "light row". If it's 3299, it should be called "U".

**Comment by Mapaler** [comment]
My subscription will look for other ways to fix.

China has a large player base, but it's unfortunate not being able to access Google.
Most P&D Android player are installed by sharing apk with other players. (Apple Store can be accessed.)
I hope you can provide a way to distribute APK that China can access.
But most people can't access Google and subscribe, naturally you won't get revenue.
<hr>
If you want to learn about Chinese software solutions.
Many Chinese developers offer both Google and Alipay payment channels. To avoid Google's development guidelines, different APK is provided. But you can also get a subscription to Alipay by entering the order number in Google version. Because the operation is relatively complex, this is paid annually.

Consider the following points:
* Provide annual payments to reduce refresh subscriptions.
* Provide an annually paid activation code where Amazon or small sellers can sell items (China has Alibaba's Taobao.com). Even use PayPal to manually transfer money when the number of customers is small (China uses Alipay). Enter activation in the software.

These are not requirements and recommendations. Just share some information that you might be interested in.

**Comment by puzzled-dragon** [comment]
Alright, thanks for the info.
P&D Helper is only a side project (started a looong time ago), and I don't hope to make money with it.
There is so few people on it that I don't think the potential (pecuniary) benefit would be worth implementing another payment option (as I don't have as much time as I used to) 😅.
But it's always good to know how other countries work, if I ever want to deploy a paid app in China.

As for the APK, I gladly send it to anyone who is contacting me by email.
I could put them on here, but I don't know if it would be useful...

Good evening

**Comment by puzzled-dragon** [comment]
> So, which is Tifa(uevo)? No.3298 or 3299? In China, the most use is 3298, so I named it "light row". If it's 3299, it should be called "U".

Uevo Tifa is 3298 !
Following the same logic, 3299 would be "uuevo" (ultimate ultimate evolution) in US.

**Pull request merged**
